# Generated by Django 3.1.1 on 2020-09-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
